.drone.yml
src/app/@core/models/respuesta.ts
src/app/@core/models/tabla_resoluciones.ts
src/app/app.component.scss
src/app/app.component.spec.ts
src/app/pages/form-detalle-resolucion/form-detalle-resolucion.component.html
src/app/pages/form-detalle-resolucion/form-detalle-resolucion.component.spec.ts
src/app/pages/form-detalle-resolucion/form-detalle-resolucion.component.ts
src/app/pages/gestion-resoluciones/consulta-docente/consulta-docente.component.spec.ts
src/app/pages/gestion-resoluciones/consulta-docente/consulta-docente.component.ts
src/app/pages/gestion-resoluciones/detalle-resolucion/detalle-resolucion.component.spec.ts
src/app/pages/gestion-resoluciones/generacion-resolucion/generacion-resolucion.component.html
src/app/pages/gestion-resoluciones/generacion-resolucion/generacion-resolucion.component.spec.ts
src/app/pages/gestion-resoluciones/generacion-resolucion/generacion-resolucion.component.ts
src/app/pages/gestion-resoluciones/gestion-resoluciones.component.spec.ts
src/app/pages/gestion-resoluciones/gestion-resoluciones.component.ts
src/app/pages/plantillas/plantillas.component.html
src/app/pages/plantillas/plantillas.component.spec.ts
src/app/pages/plantillas/plantillas.component.ts
src/app/pages/services/utilService.ts
src/styles.scss

feat: Se ajustan funcionalidades según hallazgos en pruebas funcionales udistrital/resoluciones_mid_v2#13

feat: optimizacion pruebas funcionales

---

src/app/@core/models/cambio_vinculacion.ts
src/app/@core/models/vinculaciones.ts
src/app/pages/form-detalle-resolucion/form-detalle-resolucion.component.html
src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.html
src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.scss
src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/listar-vinculaciones/listar-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/modal-adiciones/modal-adiciones.component.html
src/app/pages/gestion-vinculaciones/modal-adiciones/modal-adiciones.component.scss
src/app/pages/gestion-vinculaciones/modal-adiciones/modal-adiciones.component.ts
src/app/pages/gestion-vinculaciones/modal-disponibilidad/modal-disponibilidad.component.html
src/app/pages/gestion-vinculaciones/modal-disponibilidad/modal-disponibilidad.component.ts
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.html
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.scss
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.ts
src/app/pages/gestion-vinculaciones/tablas-disponibilidades/tablas-disponibilidades.component.ts
src/app/pages/gestion-vinculaciones/vincular-docentes/vincular-docentes.component.ts
src/app/pages/services/errorManager.ts
src/app/pages/services/utilService.ts
src/environments/environment.dev.ts
src/environments/environment.prod.ts
src/environments/environment.test.ts
src/environments/environment.ts

feat: Funciones del módulo de vinculaciones

feat: Funciones del módulo de vinculaciones

---

.drone.yml
src/app/@core/components/resoluciones-data-source/resoluciones-data-source.component.spec.ts
src/app/@core/components/resoluciones-data-source/resoluciones-data-source.component.ts
src/app/pages/admin-resoluciones/admin-resoluciones.component.ts
src/app/pages/admin-resoluciones/expedir-cancelacion/expedir-cancelacion.component.ts
src/app/pages/aprobacion-resoluciones/aprobacion-resoluciones.component.ts
src/app/pages/gestion-resoluciones/consulta-docente/consulta-docente.component.html
src/app/pages/gestion-resoluciones/generacion-resolucion/generacion-resolucion.component.ts
src/app/pages/gestion-resoluciones/gestion-resoluciones.component.ts

fix: Se corrige carga de resoluciones personalizando el ServerDataSource

fix: Se corrige carga de resoluciones 

---

src/app/pages/admin-resoluciones/expedir-cancelacion/expedir-cancelacion.component.html
src/app/pages/admin-resoluciones/expedir-modificacion/expedir-modificacion.component.html
src/app/pages/admin-resoluciones/expedir-vinculacion/expedir-vinculacion.component.html

hotfix: Se agrega nombre de campo para fecha de expedición

hotfix: Se agrega nombre de campo para fecha de expedición

---

src/app/@core/components/resoluciones-data-source/resoluciones-data-source.component.ts
src/app/loader/interceptor.service.ts
src/app/pages/admin-resoluciones/admin-resoluciones.component.ts
src/app/pages/admin-resoluciones/expedir-vinculacion/expedir-vinculacion.component.ts
src/app/pages/form-detalle-resolucion/form-detalle-resolucion.component.ts
src/app/pages/gestion-resoluciones/generacion-resolucion/generacion-resolucion.component.ts
src/app/pages/gestion-vinculaciones/tablas-disponibilidades/tablas-disponibilidades.component.ts
src/app/pages/gestion-vinculaciones/vincular-docentes/vincular-docentes.component.ts

management: Correcciones menores.

management: Correcciones menores.

---

src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.html

fix: ajuste campo FechaInicio en modal de reducciones.

fix: ajuste campo FechaInicio en modal de reducciones.

---

src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.ts

fix: Se corrige dato en reducción.

fix: Se corrige dato en reducción.

---

src/app/pages/gestion-vinculaciones/listar-vinculaciones/listar-vinculaciones.component.ts

fix: se actualiza tabla de vinculaciones al registrar modificaciones.

fix: se actualiza tabla de vinculaciones

---

src/environments/environment.prod.ts

fix: se actualiza cliente_id en prod

fix: se actualiza cliente_id en prod

---

src/environments/environment.prod.ts

management: actualizacion cliente_id

management: actualizacion cliente_id

---

src/app/@core/components/resoluciones-data-source/resoluciones-data-source.component.ts
src/app/@core/models/tabla_resolucion.ts
src/app/@core/models/tabla_resoluciones.ts
src/app/@core/models/vinculacion_tercero.ts
src/app/app.component.scss
src/app/pages/admin-resoluciones/admin-resoluciones.component.html
src/app/pages/admin-resoluciones/admin-resoluciones.component.ts
src/app/pages/aprobacion-resoluciones/aprobacion-resoluciones.component.html
src/app/pages/aprobacion-resoluciones/aprobacion-resoluciones.component.ts
src/app/pages/gestion-resoluciones/consulta-docente/consulta-docente.component.ts
src/app/pages/gestion-resoluciones/generacion-resolucion/generacion-resolucion.component.html
src/app/pages/gestion-resoluciones/generacion-resolucion/generacion-resolucion.component.ts
src/app/pages/gestion-resoluciones/gestion-resoluciones.component.html
src/app/pages/gestion-resoluciones/gestion-resoluciones.component.ts
src/app/pages/gestion-vinculaciones/vincular-docentes/vincular-docentes.component.ts
src/app/pages/pages.component.ts
src/app/pages/pages.module.ts
src/app/pages/services/userService.ts
src/styles.scss

feat: filtros de búsqueda completos #64 udistrital/resoluciones_mid_v2#46

feat: filtros de búsqueda completos

---

src/app/@core/models/carga_lectiva.ts
src/app/pages/dashboard/dashboard.component.html
src/app/pages/dashboard/dashboard.component.scss
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/gestion-vinculaciones/vincular-docentes/vincular-docentes.component.ts

feat: ajustes adicionales. resolves #72

feat: ajustes adicionales

---

src/app/@core/components/actions-assistance/actions-assistance.component.scss
src/app/pages/dashboard/dashboard.component.scss
src/app/pages/form-detalle-resolucion/form-detalle-resolucion.component.html
src/app/pages/gestion-resoluciones/generacion-resolucion/generacion-resolucion.component.html
src/app/pages/gestion-resoluciones/generacion-resolucion/generacion-resolucion.component.ts
src/app/pages/gestion-resoluciones/gestion-resoluciones.component.html
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.ts
src/app/pages/gestion-vinculaciones/tablas-disponibilidades/tablas-disponibilidades.component.ts
src/app/pages/gestion-vinculaciones/vincular-docentes/vincular-docentes.component.ts
src/app/pages/pages.component.ts
src/app/pages/plantillas/plantillas.component.scss
src/app/pages/services/userService.ts
src/styles.scss

feat: estilos responsive y lint errors. resolves #73

feat: estilos responsive y lint errors.

---

src/app/pages/gestion-vinculaciones/modal-adiciones/modal-adiciones.component.html
src/app/pages/gestion-vinculaciones/modal-adiciones/modal-adiciones.component.ts
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.html
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.ts

feat: Visualización del numero de semanas segun la fecha de inicio elegida. resolves #74

feat: Visualización del numero de semanas

---

src/app/@core/components/guard/nav.guard.spec.ts
src/app/@core/components/guard/nav.guard.ts
src/app/@core/components/guard/role.guard.spec.ts
src/app/@core/components/guard/role.guard.ts
src/app/pages/gestion-resoluciones/consulta-docente/consulta-docente.component.ts
src/app/pages/gestion-resoluciones/detalle-resolucion/detalle-resolucion.component.ts
src/app/pages/gestion-resoluciones/generacion-resolucion/generacion-resolucion.component.ts
src/app/pages/gestion-resoluciones/gestion-resoluciones.component.ts
src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/listar-vinculaciones/listar-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/vincular-docentes/vincular-docentes.component.ts
src/app/pages/pages-routing.module.ts
src/app/pages/pages.component.ts
src/app/pages/pages.module.ts
src/app/pages/services/utilService.ts

feat: Control de acceso mediante guards. resolves #75

feat: Control de acceso mediante guards

---

src/app/pages/form-detalle-resolucion/form-detalle-resolucion.component.ts
src/app/pages/plantillas/plantillas.component.html
src/app/pages/plantillas/plantillas.component.ts

feat: Se agrega a módulo de plantillas funcionalidad para copiar plantilla. resolves #79

feat: Se agrega funcionalidad para copiar plantillas

---

src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.html
src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/listar-vinculaciones/listar-vinculaciones.component.html
src/app/pages/gestion-vinculaciones/listar-vinculaciones/listar-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/vincular-docentes/vincular-docentes.component.html
src/app/pages/gestion-vinculaciones/vincular-docentes/vincular-docentes.component.ts

feat: Se ajusta captura de datos en cancelación para posgrado. resolves #80

feat: Se ajusta captura de datos en cancelación posgrado.

---

.drone.yml
README.md
src/app/@core/components/actions-assistance/actions-assistance.component.html
src/app/@core/components/rp-selector/rp-selector.component.html
src/app/@core/components/rp-selector/rp-selector.component.spec.ts
src/app/@core/components/rp-selector/rp-selector.component.ts
src/app/@core/models/rp_seleccionado.ts
src/app/pages/gestion-resoluciones/gestion-resoluciones.component.ts
src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/listar-vinculaciones/listar-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/rp-vinculaciones/rp-vinculaciones.component.html
src/app/pages/gestion-vinculaciones/rp-vinculaciones/rp-vinculaciones.component.scss
src/app/pages/gestion-vinculaciones/rp-vinculaciones/rp-vinculaciones.component.spec.ts
src/app/pages/gestion-vinculaciones/rp-vinculaciones/rp-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/vincular-docentes/vincular-docentes.component.ts
src/app/pages/pages-routing.module.ts
src/app/pages/pages.module.ts

feat: Se desarrolla funcionalidad de selección de Registros presupuestales. resolves #85

feat: funcionalidad de selección de Registros presupuestales

---

src/app/@core/components/rp-selector/rp-selector.component.ts
src/app/pages/gestion-vinculaciones/listar-vinculaciones/listar-vinculaciones.component.ts

feat: Se condiciona consulta de semáforo solo para ambiente de producción. #93

feat: Se condiciona consulta de semaforo

---

src/app/@core/components/guard/nav.guard.ts
src/app/@core/components/rp-selector/rp-selector.component.html
src/app/@core/components/rp-selector/rp-selector.component.ts
src/app/@core/models/plantilla.ts
src/app/pages/admin-resoluciones/admin-resoluciones.component.html
src/app/pages/admin-resoluciones/admin-resoluciones.component.ts
src/app/pages/admin-resoluciones/expedir-cancelacion/expedir-cancelacion.component.html
src/app/pages/admin-resoluciones/expedir-cancelacion/expedir-cancelacion.component.ts
src/app/pages/admin-resoluciones/expedir-modificacion/expedir-modificacion.component.ts
src/app/pages/aprobacion-resoluciones/aprobacion-resoluciones.component.html
src/app/pages/aprobacion-resoluciones/aprobacion-resoluciones.component.ts
src/app/pages/form-detalle-resolucion/form-detalle-resolucion.component.ts
src/app/pages/gestion-resoluciones/generacion-resolucion/generacion-resolucion.component.html
src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/listar-vinculaciones/listar-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/modal-adiciones/modal-adiciones.component.html
src/app/pages/gestion-vinculaciones/modal-adiciones/modal-adiciones.component.ts
src/app/pages/gestion-vinculaciones/modal-disponibilidad/modal-disponibilidad.component.html
src/app/pages/gestion-vinculaciones/modal-disponibilidad/modal-disponibilidad.component.ts
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.html
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.ts
src/app/pages/gestion-vinculaciones/rp-vinculaciones/rp-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/tablas-disponibilidades/tablas-disponibilidades.component.html
src/app/pages/gestion-vinculaciones/tablas-disponibilidades/tablas-disponibilidades.component.ts
src/app/pages/pages-routing.module.ts
src/app/pages/plantillas/plantillas.component.ts

fix: Correccion de hallazgos encontrados en preparación de pruebas piloto

fix: Correccion de hallazgos encontrados en preparación de pruebas piloto

---

.drone.yml
package-lock.json
package.json
src/app/@core/models/acta_inicio.ts
src/app/@core/models/cambio_vinculacion.ts
src/app/pages/admin-resoluciones/expedir-cancelacion/expedir-cancelacion.component.ts
src/app/pages/admin-resoluciones/expedir-modificacion/expedir-modificacion.component.ts
src/app/pages/admin-resoluciones/expedir-vinculacion/expedir-vinculacion.component.ts
src/app/pages/gestion-resoluciones/gestion-resoluciones.component.ts
src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.html
src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/modal-adiciones/modal-adiciones.component.html
src/app/pages/gestion-vinculaciones/modal-adiciones/modal-adiciones.component.ts
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.html
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.ts
src/app/pages/gestion-vinculaciones/tablas-disponibilidades/tablas-disponibilidades.component.html

feat: Ajustes fechas

---

src/app/@core/models/cambio_vinculacion.ts
src/app/@core/models/vinculaciones_aux.ts
src/app/pages/gestion-vinculaciones/listar-vinculaciones/listar-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.html
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.ts

feat: reducciones posgrado #137

---

src/app/@core/models/cambio_vinculacion.ts
src/app/@core/models/vinculaciones_aux.ts
src/app/pages/form-detalle-resolucion/form-detalle-resolucion.component.ts
src/app/pages/gestion-vinculaciones/listar-vinculaciones/listar-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.html
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.ts

reducciones posgrado

---

src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.html
src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.scss
src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.ts

feat: Cancelacion posgrado 

---

src/app/@core/models/tabla_vinculaciones.ts
src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.ts
src/app/pages/gestion-vinculaciones/vincular-docentes/vincular-docentes.component.ts

feat: Adición de campos desagregado reporte excel

---

src/app/@core/components/guard/role.guard.ts
src/app/@core/models/datos_reporte.ts
src/app/@core/models/reporte_financiera.ts
src/app/pages/gestion-vinculaciones/vincular-docentes/vincular-docentes.component.ts
src/app/pages/pages-routing.module.ts
src/app/pages/pages.module.ts
src/app/pages/reporte-financiera/reporte-financiera.component.html
src/app/pages/reporte-financiera/reporte-financiera.component.scss
src/app/pages/reporte-financiera/reporte-financiera.component.spec.ts
src/app/pages/reporte-financiera/reporte-financiera.component.ts

Reporte financiera

---

src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.html
src/app/pages/gestion-vinculaciones/cancelar-vinculaciones/cancelar-vinculaciones.component.ts

fix: Ajuste para permitir mas semanas de cancelación

---

src/app/app.component.scss
src/app/pages/admin-resoluciones/expedir-vinculacion/expedir-vinculacion.component.scss
src/app/pages/admin-resoluciones/expedir-vinculacion/expedir-vinculacion.component.ts
src/app/pages/gestion-vinculaciones/modal-adiciones/modal-adiciones.component.html
src/app/pages/gestion-vinculaciones/modal-adiciones/modal-adiciones.component.ts
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.html
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.scss
src/app/pages/gestion-vinculaciones/modal-reducciones/modal-reducciones.component.ts

se agregan tips en campos para los modales de expedición, adiciones, reducciones

feat: #196 tips para el usuario

---

src/app/pages/gestion-resoluciones/generacion-resolucion/generacion-resolucion.component.ts

consulta de vigencia de carga academica de la resolución anterior para que sea asignada a la resolución modificatoria

fix: periodo carga academica

---

src/app/pages/gestion-resoluciones/generacion-resolucion/generacion-resolucion.component.ts

se consulta vigencia y periodo de la carga academica usada en la resolucion anterior para resoluciones modificatorias

fix: vigencia carga en novedad

---

src/app/@core/models/datos_reporte.ts
src/app/pages/pages.module.ts
src/app/pages/reporte-financiera/reporte-financiera.component.html
src/app/pages/reporte-financiera/reporte-financiera.component.ts

Se corrige para usar data de mock temporalmente en reportes consolidados como prueba

reportes financiera con data mock

---

src/index.html

fix reporte financiera

---

src/app/pages/admin-resoluciones/expedir-vinculacion/expedir-vinculacion.component.ts
src/app/pages/form-detalle-resolucion/form-detalle-resolucion.component.ts

udistrital/resoluciones_cliente_v2#229 resoluciones_cliente_v2 a prod

hotfix: actualizacion de resoluciones_cliente_v2 udistrital/resoluciones_cliente_v2#229
